### ISSUE TITLE
New subset interface: categorical metadata values are unsorted

### ISSUE THREAD

**Issue by wish1832** [amc-heme/scExploreR#235]
Categorical metadata entries in the subset menus do not appear to be ordered (screenshot below).

<img width="266" alt="Screenshot 2023-10-19 at 2 56 48 PM" src="https://github.com/amc-heme/scExploreR/assets/45372167/49d95ddf-a42e-4b46-8910-7f93cdfb97aa">

**Comment by jairav** [comment]
change the menu population code to check for class. if a factor, call levels. Else, call unique with alphanumeric sorting. 

this behavior should be added to docs
