### ISSUE TITLE
Config app crashes when pressing "Load config file" when no config path is defined

### ISSUE THREAD

**Issue by wish1832** [amc-heme/scExploreR#241]
When loading a config app with nothing passed to `config_path`, the "Load config file" button is still active, and when pressed the app will crash. 

There are a few possible solutions:

1. Hide/disable the button when no config file is passed via `config_path`.
2. Load config file fields automatically on startup when the user provides a file to this argument.
3. Have a file uploader pop up when the load config button is pressed.

**Comment by jairav** [comment]
added special case for crash condition in ce11ecc. Maintains consistent behavior with modal.
