### ISSUE TITLE
Inspect numeric threshold based DGE for data with NA values

### ISSUE THREAD

**Issue by wish1832** [amc-heme/scExploreR#255]
When performing DGE based on a simple numeric threshold, it is possible to encounter a feature with NA values. In this situation, results may differ if the cells with NA values are included in the differential expression computation, as the results would compare cells in each level of the binary threshold to the other cells _and cells with NA values_. The process of DGE computation in the app should be inspected to determined if NA values are included or excluded, and this should be adjusted accordingly to ensure accurate results are being returned.

**Comment by jairav** [comment]
@wish1832 @agillen an object with NAs is required to complete this

**Comment by wish1832** [comment]
@srg0502 and I found that objects with NA values cause errors in differential expression. It does likely that a user would create objects with NA values, however. We should put a warning in our object setup vignette (#277) that users should not put NA values in expression data, and we should also have the config app throw a warning notification when NA values are detected in expression data for any modality.

**Comment by wish1832** [comment]
The priority is to put a note in the documentation that NAs should not be included for feature expression data. #327 catches the issues, but it uses anyNA methods that don't work for BPCells matrices. An equivalent of anyNA should be implemented, but this is of lower priority.
