### ISSUE TITLE
Issue with updating DEG list in scExploreR-AML

### ISSUE THREAD

**Issue by anavujovic1** [amc-heme/scExploreR#257]
<img width="1705" alt="Screenshot 2024-03-11 at 8 31 50 PM" src="https://github.com/amc-heme/scExploreR/assets/163082875/ecef07df-271c-46c4-8cbe-d0f0e9242e90">

**Comment by agillen** [comment]
This is solved in the currently deployed browsers by explicitly installing scDE before scExploreR in the Dockerfile, but I'm leaving this issue open pending further investigation because adding scDE as a dependency alone (see 1fdc8dd and be8eef1) didn't resolve the issue.
