### ISSUE TITLE
Gene correlation issue

### ISSUE THREAD

**Issue by sheltoia** [amc-heme/scExploreR#258]
Whenever I press submit for a gene correlation query I get disconnected from the server

**Comment by agillen** [comment]
Gene correlation is indeed broken for all supported objects except Seurat objects using standard (pre-Assay5) assays objects. @wish1832 - we may want to consider disabling the correlation tab either as a config option or based on object type.

**Comment by jairav** [comment]
This feature will be removed, and alternate analysis approaches investigated.
