### ISSUE TITLE
The DGE is spitting out a feature number instead of gene name 

### ISSUE THREAD

**Issue by anavujovic1** [amc-heme/scExploreR#259]
<img width="1673" alt="Screenshot 2024-03-12 at 11 33 05 AM" src="https://github.com/amc-heme/scExploreR/assets/163082875/c0106eca-64a1-49f9-aade-771ed25b6ce9">

**Comment by agillen** [comment]
Practically addressed for AMC deployed browsers upstream with amc-heme/scDE@4fcde4c. Issue amc-heme/scDE#1 will track a more durable fix.
