### ISSUE TITLE
Object dictionary: metadata description cards have blank headers when metadata labels are not defined in the config app

### ISSUE THREAD

**Issue by wish1832** [amc-heme/scExploreR#263]
If a metadata variable is added in the config app and a label is not chosen, the "card" for displaying the metadata description in the auto-generated object dictionary will have a blank header (see screenshot below). If a label is not defined for a metadata variable, the header should show the name of the metadata variable as defined in object metadata, instead of being blank.

![Screenshot 2024-03-20 at 12 36 48 PM](https://github.com/amc-heme/scExploreR/assets/45372167/e2fb2c52-7969-4f18-9ac4-500210c79297)

Similarly, if a description is not entered for a variable, the content of the card will be blank. To the end user, it is not clear whether the description was intentionally not provided, or if this is a bug.

**Comment by srg0502** [comment]
This behavior occurs even when a label is chosen. The header appears to be blank, even though the label appears in the HTML code for the element.
