### ISSUE TITLE
Disable accept subset button while filters are being edited

### ISSUE THREAD

**Issue by wish1832** [amc-heme/scExploreR#265]
When editing subset filters, the "apply subset" button in the plots tab (or the "update" button in the dge tab) can be pressed before confirming or cancelling the filter. If the user presses this button, the filter being edited will not be applied, and the app can crash if the user then confirms the filter and runs the subset. The apply subset button should be disabled while filters are being edited.

![Screenshot 2024-03-26 at 12 26 56 PM](https://github.com/amc-heme/scExploreR/assets/45372167/08968b87-4c5b-4492-afc4-573b38bded74)

**Comment by srg0502** [comment]
the apply subset button is disabled

**Comment by wish1832** [comment]
I confirmed that this has already disabled on the version in `main`. There may be a weird edge case where the "apply subset" button is not disabled while the edit window is open, though I haven't yet been able to find one. If one is found, we should re-open the issue with the specific edge case.
