### ISSUE TITLE
Infinite loop in plots tab

### ISSUE THREAD

**Issue by wish1832** [amc-heme/scExploreR#266]
An infinite loop was observed in the plots tab when manual plot dimensions were being edited. The infinite loop has not yet been reproduced.

**Comment by jairav** [comment]
Attempting to reproduce

**Comment by jairav** [comment]
I am able to inconsistently reproduce the behavior ([link](https://github.com/amc-heme/scExploreR/assets/44884343/d41c6a56-a68a-4fb2-a680-9a9e65c6382d)). 

I am able to reproduce this is by having multiple (3+) plots, setting all plots to manual, and then trying to rapidly change dimensions on one. It flips between current and previous state in an infinite loop.

**Comment by jairav** [comment]
Will try to reproduce behavior with text boxes removed. If this eliminates the issue, we will decide between ui elements.
