### ISSUE TITLE
Error when making blended feature plot

### ISSUE THREAD

**Issue by wish1832** [amc-heme/scExploreR#280]
When requesting a blended feature plot with two features, the following error was returned: "Error: unused argument (split.by = if (split_by != "none") split_by else NULL)"

This is likely related to the plotting functions currently in SCUBA, which now use `split_by` instead of `split.by`.

**Comment by wish1832** [comment]
This issue has likely been in the app since SCUBA was added, and underlies the need for automated testing (#203)

**Comment by jairav** [comment]
turns out this is a SCUBA error. Resolved in this PR: https://github.com/amc-heme/SCUBA/pull/86
