### ISSUE TITLE
Add Documentation for the current subsetting interface

### ISSUE THREAD

**Issue by wish1832** [amc-heme/scExploreR#303]
The subsetting documentation in the "full documentation" vignette has not been updated since the latest subsetting interface was released, and there are no vignettes that describe this interface. Documentation should be added or updated to describe the latest interface.

**Comment by jairav** [comment]
This applies to the subsets in either the Plots tab or before DGE is done.  There should be a glaring difference in between the scExploreR docs and the current ui for subsetting.

**Comment by srg0502** [comment]
The "forming subsets" section of the full documentation has been updated in the #276 branch.

**Comment by srg0502** [comment]
Closing this issue without merging the branch until all documentation is reviewed.
