### ISSUE TITLE
Error when running differential expression

### ISSUE THREAD

**Issue by jlbecker1** [amc-heme/scExploreR#306]
Hello,
When I attempt to run differential expression I receive an error related to the DGE table column names. I am working with a Seurat object saved as an .rds file (Seurat version 4.3.0). I am able to run differential expression using presto on it's own with the same Seurat object.  I have no issue making any of the plots available, it's just the gene expression. The console shows: 
2024-05-31 14:43:02.745038 [INFO] DGE Tab: Begin Presto
[1] "DGE table colnanes"
NULL
 Screen shot of app:
![image](https://github.com/amc-heme/scExploreR/assets/125772834/e64d2388-d438-4107-9201-dda04b65bce9)

**Comment by wish1832** [comment]
Hi Jennifer,

Thanks for reaching out. Can you send me the text in the grey notification on the right of the screen? If possible, please include the beginning too, which likely got cut off. You may be able to get the full message by right-clicking on the notification text and selecting "select element" to open your browser's console.

I'll push an update to print this info in the console logs too, to make this process easier.

All the best,

Bill Showers

**Comment by jlbecker1** [comment]
Hi Bill,
Thank you for getting back to be so quickly. When I choose select element I am able to see the full error message. The first line is "Error: `features` must be one of "Xkr4", "Rp1 (long list of genes here)"  and the last line is "not "data".." I'm able to make feature plots with no issue so I know that the gene names are there.

**Comment by jlbecker1** [comment]
I just wanted to add an update that this happens to me when I use the triana_et_al_condensed data from your GitHub as well. Thanks again for your help.

**Comment by wish1832** [comment]
Hi Jennifer,

Apologies for the delay in response. I attempted to re-create this with the triana_et_al_condensed data, and was unable to do so. Could you send me a screenshot of the Differential Expression tab with this object, showing the selections you made before pressing "Update"?

**Comment by jlbecker1** [comment]
This is what I tried most recently 
<img width="627" alt="image" src="https://github.com/user-attachments/assets/af9f5c91-ee1e-4eb5-814b-30f22e1d0fc1">

**Comment by agillen** [comment]
Can confirm that this is definitely Seurat 4.x.x-specific. Upgrading to Seurat 5.x.x will solve it, but recognize that might not be practical. We'll try to track down the underlying issue today.

**Comment by wish1832** [comment]
This is linked to a programming issue in a dependency we manage, that causes issues when using Seurat 4.x.x.
amc-heme/scDE#6

**Comment by wish1832** [comment]
Hi Jennifer,

We found the underlying cause of the issue and fixed it. Could you re-install the latest version of scExploreR, and the scDE package?

`remotes::install_github("amc-heme/scExploreR")`
`remotes::install_github("amc-heme/scDE")`

**Comment by agillen** [comment]
Resolved with amc-heme/scDE#7.

@jlbecker1 - thanks so much for reporting this issue. Can you please confirm that reinstalling scDE from GitHub resolves this for you?

`remotes::install_github("amc-heme/scDE")`

**Comment by wish1832** [comment]
And in case updating scDE causes different issues, please try updating scExploreR, and contact us if that does not work. 

`remotes::install_github("amc-heme/scExploreR")`

**Comment by jlbecker1** [comment]
Yes, this worked. Thank you so much for your help!
