### ISSUE TITLE
Anndata objects containing embeddings in obsm with more than one underscore in name produce an error

### ISSUE THREAD

**Issue by agillen** [amc-heme/scExploreR#310]
Note that this may be an amc-heme/scuba issue, but it's release critical for scExploreR.

This issue is specific to anndata objects and appears to be related to how scExploreR (or SCUBA) builds dim names(?).

scExploreR works as expected with embeddings stored in `.obsm` when named:

X_umap
X_pca
X_totalVI

But fails with the following error when named "X_totalVI_ref":
`Error: KeyError: "None of [Index(['ref_1', 'ref_2'], dtype='object')] are in the [columns]"`

and similarly with the following error when named "X_umap_ccmt":
`Error: KeyError: "None of [Index(['ccmt_1', 'ccmt_2'], dtype='object')] are in the [columns]"`

**Comment by jairav** [comment]
closed as part of #90
