### ISSUE TITLE
expose prefix arg for loadHDF5SummarizedExperiment

### ISSUE THREAD

**Issue by kriemo** [amc-heme/scExploreR#363]
If a disk-backed SCE is named with a non-default prefix (other than `se.rds` and `assays.h5`) it can't be loaded into scExploreR. The app doesn't expose the `prefix` argument for `loadHDF5SummarizedExperiment` to the user, which is necessary to indicate the correct SCE to load within a directory. 

Perhaps `run_config()` could gain another parameter such as `HDF5_prefix`, whose value could then be recorded in the config.yml?

happy to draft a PR if that makes sense.

**Comment by wish1832** [comment]
Hey Kent, 

This sounds like a good idea, it seems likely that other SCE users will run into this. Go for it! 

When adding this, an additional change will be needed so run_scExploreR will work correctly. Currently the state of ` is_HDF5SummarizedExperiment` when running the config app is recorded in the config file when it is saved. The config file in turn then instructs scExploreR to use `loadHDF5SummarizedExperiment` if this is TRUE. The path will also need to be recorded in the config file to tell scExploreR what `path` parameter to supply to `loadHDF5SummarizedExperiment`. 

For reference, below is the code from `run_config_app` used to set `is_HDF5SummarizedExperiment`.

```
# Initialize Variables
      # config_data: list used to store full record of user selections
      # across all tabs
      config_data <-
        list(
          # Append config app version to list that is printed to file
          `config_version` = config_version,
          # Record class of object
          `object_class` = is(object),
          # Record if a SingleCellExperiment object is HDF5 enabled
          `is_HDF5SummarizedExperiment` = is_HDF5SummarizedExperiment
          )
```
