### ISSUE TITLE
Subsetting drops all cells with NA in any metadata column

### ISSUE THREAD

**Issue by agillen** [amc-heme/scExploreR#65]
We've discussed NA handling, but I don't recall if it was in this context, specifically.

An example:

Suppose two metadata columns are present in a config file: `sample` and `cluster`

Now suppose a cell has `sample = "Sample1"` and `cluster = NA`.

Subsetting to include `"Sample1"` removes this cell, even with no explicit subsetting of the `cluster` values.

**Comment by wish1832** [comment]
@agillen @jairav @srg0502 Here's an additional release critical bug. The worst effects of NA literals in metadata have been controlled for (at least, the ones we're aware of), but we should add in the object generation documentation (#277) that NA literals in metadata tables are strongly discouraged.

**Comment by agillen** [comment]
Should the config app throw a warning when loading an object if any metadata column includes NA literals?

**Comment by wish1832** [comment]
We could also do this in the main app, for variables that are in the config file.
